repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-yaml
      exclude: invalidFile.yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=800']
    - id: check-json
      # should exclude invalid file and
      # the ones with c++ comments which is not part of standard
      exclude: |
        (?x)(
          invalidFile.json$|
          SkipValidationsTemplates.json$|
          tsconfig.json$|
          ^Solutions/Templates/mainTemplate.json$|
          ^Solutions/Templates/createUIDefinition.json$|
          ^Solutions/Templates/Example/EXAMPLE-mainTemplate.json$
        )
    - id: pretty-format-json
      args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
      exclude: |
        (?x)(
          invalidFile.json$|
          SkipValidationsTemplates.json$|
          tsconfig.json$|
          ^Solutions/Templates/mainTemplate.json$|
          ^Solutions/Templates/createUIDefinition.json$|
          ^Solutions/Templates/Example/EXAMPLE-mainTemplate.json$
        )
    - id: detect-private-key
    - id: check-case-conflict
    - id: requirements-txt-fixer
