repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-yaml
      exclude: invalidFile.yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=800']
    - id: check-json
      # should exclude invalid file and
      # the ones with c++ comments which is not part of standard
      exclude: |
        (?x)(
          invalidFile.json$|
          SkipValidationsTemplates.json$|
          tsconfig.json$|
          ^Solutions/Templates/mainTemplate.json$|
          ^Solutions/Templates/createUIDefinition.json$|
          ^Solutions/Templates/Example/EXAMPLE-mainTemplate.json$
        )
    - id: pretty-format-json
      args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
      # same than above
      # FIXME! 4 workbooks and after (ok check-json)
      exclude: |
        (?x)(
          invalidFile.json$|
          SkipValidationsTemplates.json$|
          tsconfig.json$|
          ^Solutions/Templates/mainTemplate.json$|
          ^Solutions/Templates/createUIDefinition.json$|
          ^Solutions/Templates/Example/EXAMPLE-mainTemplate.json$|
          ^Workbooks/Barracuda.json$|
          ^Workbooks/pfsense.json$|
          ^Workbooks/WebApplicationFirewallFirewallEvents.json$|
          ^Workbooks/WebApplicationFirewallOverview.json$|
          ^.script/tests/KqlvalidationsTests/CustomTables/VectraStream_CL.json$
        )
    - id: detect-private-key
    - id: check-case-conflict
    - id: requirements-txt-fixer
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
    - id: codespell
      args: [-I, .codespellignore, --ignore-regex, '\\[fnrstv]']
      exclude: |
        (?x)(
          ^BYOML/|
          ^DataConnectors/|
          ^Hunting\sQueries/|
          ^MasterPlaybooks/|
          ^Parsers/|
          ^Playbooks/|
          ^Sample\sData|
          ^Solutions/|
          ^Tools/|
          ^Tools/MITREATT&CK-LayerGeneration-Notebook/|
          ^Tools/Sample\sCode/|
          ^Workbooks/
        )
